AllCops:
  TargetRubyVersion: 2.5

Style/EmptyCaseCondition:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/ParallelAssignment:
  Enabled: false

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 124
  AllowURI: true
  URISchemes:
    - http
    - https

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Enabled: false
